spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/idowhatiwant
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
